theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0

[editor.statusline]
left = ["spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position-percentage", "position"]

[keys.insert.j]
d = "normal_mode"
j = "@<esc>:insert-output echo -n j<ret>lij"

[keys.normal]
X  = "extend_line_above"
# on-startup = "@<C-f>" # This is not a feature in helix yet
C-f = '@:new<ret>:insert-output lf -print-last-dir -print-selection<ret>s[ \\]<ret>i\jd,ggx:change-current-directory <C-r>.<ret>dx\"fd:buffer-close!<ret>:open <C-r>f<ret><esc>:redraw<ret>'

[keys.normal.g]
# I use these keybindings to go to where I should hard wrap lines in a project
# TODO: These should not go onto the next line when it is less than the
#       specified width.
6 = "@gh59l"
7 = "@gh69l"
8 = "@gh79l"
9 = "@gh89l"
0 = "@gh99l"
1 = "@gh109l"
2 = "@gh119l"
3 = "@gh129l"
4 = "@gh139l"
5 = "@gh149l"

[keys.normal.space.space]
# Aligns every row in a markdown table, only works given the following assemptions:
# - The table is in a seperate paragraph
# - The table has a table header seperator
a = """@\
  <C-s>\
  map<A-;>gjxvhs[^\\|]<ret><A-d>\
  x<A-;>vls\\|<ret>i - <esc>\
  maps +\\|<ret>vh<A-d>\
  maps[^\\\\\\n](\\\\\\\\)*\\|<ret>vls\\|<ret>i <esc>&\
  map<A-;>gjxvh<A-;>lS\\|<ret>h<A-;>lr-\
  6<C-o>\
"""
# Explanation:
# - The `@` makes this [a macro keybinding](https://helix-editor.com/news/release-25-01-highlights/#macro-keybindings)
# - The 1st line saves the current cursor position to the jumplist, so it can be restored later
# - The 2nd line removes all charecters in the table header that are not `|`
# - The 3rd line inserts ` - ` before every `|` charecter in the table header
# - The 4rd line removes all the spacing between the end of the contents in a table row, and the  `|`
# - The 5th line aligns the table columns
# - The 6th line replaces the spaces in the table header with dashes
# - The 7th line jumps backwards in the jumplist to restore the cursor position
