theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0

[editor.statusline]
left = ["spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position-percentage", "position"]

[keys.insert.j]
d = "normal_mode"
j = "@<esc>:insert-output echo -n j<ret>lij"

[keys.normal]
X  = "extend_line_above"
# on-startup = "@<C-f>" # This is not a feature in helix yet
C-f = '@:new<ret>:insert-output lf -print-last-dir -print-selection<ret>s[ \\]<ret>i\jd,ggx:change-current-directory <C-r>.<ret>dx\"fd:buffer-close!<ret>:open <C-r>f<ret><esc>:redraw<ret>'

[keys.normal.space]
a = '@s([^\\](\\\\)*\|)|^\|<ret>;&' # Aligns every row in a markdown table if you have the whole table selected
