theme = "onedark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X  = "extend_line_above"

[keys.select]
f = "flip_selections"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "position-percentage", "position"]
