[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
config.config = "~/.config/typos-lsp/typos.toml"
config.diagnosticSeverity = "Info"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "toml"
language-servers = ["taplo", "tombi", "typos"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
language-servers = ["marksman", "markdown-oxide", "typos"]

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp", "typos"]

[[language]]
name = "odin"
language-servers = ["ols", "typos"]

[[language]]
name = "python"
language-servers = ["pyright", "typos"]
indent = { tab-width = 4, unit = "    " }

# TODO: Fix astro language server
#[language-server.astro-ls]
#command = "astro-ls"
#args = [ "--stdio" ]
#config = { "environment" = "node" }

#[[language]]
#name = "astro"
#scope = "source.astro"
#injection-regex = "astro"
#file-types = ["astro"]
#roots = ["package.json", "astro.config.mjs"]
#language-servers = [ "astro-ls" ]

[[language]]
name = "elm"
formatter = { command = "elm-format", args = ["--stdin"] }
language-servers = ["elm-language-server", "typos"]
